name: 部署到服务器

on:
  push:
    branches: [ main ]  # 根据您的主分支名称调整

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 添加服务器到已知主机
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: 部署到服务器
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd ${{ secrets.SERVER_PATH }} && \
          git pull && \
          docker build -t openai-proxy-manager . && \
          docker stop openai-proxy-manager || true && \
          docker rm openai-proxy-manager || true && \
          docker run -d --name openai-proxy-manager -p 30080:80 -v ${{ secrets.SERVER_PATH }}/server/data:/app/server/data openai-proxy-manager"
